services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 5

  speaker-id:
    # Use unified image with both Resemblyzer and ECAPA models
    # Switch between models using USE_ECAPA environment variable
    image: ghcr.io/identitry/speaker-id:latest

    # Option: Build locally (uncomment to use)
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile

    environment:
      - QDRANT_URL=http://qdrant:6333
      # Model selection: false = Resemblyzer (default, faster), true = ECAPA (more accurate)
      - USE_ECAPA=false
      # Audio preprocessing (all enabled by default for better accuracy)
      - AUDIO_ENHANCEMENT=true
      - SELECT_BEST_SEGMENT=true
      - SCORE_CALIBRATION=true
      - MIN_AUDIO_DURATION=1.0
      # Other settings
      - SAMPLE_RATE=16000
      - DEFAULT_THRESHOLD=0.82
      - LOG_LEVEL=INFO
    ports:
      - "8080:8080"
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped

volumes:
  qdrant-data:
